# Generated by Django 3.2.7 on 2021-11-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuingOrginizationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('api', models.URLField()),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
