# Generated by Django 3.2.7 on 2021-12-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_issuingorginizationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuingorginizationotp',
            name='images',
            field=models.URLField(default='https://test.com', null=True),
        ),
    ]
