# Generated by Django 3.2.7 on 2021-10-28 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_tokens', '0005_alter_cardtoken_date_expiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardverify',
            name='date_expiring',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 19, 48, 13, 418016)),
        ),
        migrations.AddField(
            model_name='cardverify',
            name='date_issued',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 28, 19, 42, 32, 96589)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardtoken',
            name='date_expiring',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 28, 19, 48, 13, 416730)),
        ),
        migrations.AlterField(
            model_name='cardverify',
            name='valied',
            field=models.BooleanField(default=True),
        ),
    ]
