# Generated by Django 3.2.7 on 2021-12-14 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_tokens', '0024_auto_20211213_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtoken',
            name='date_expiring',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 21, 2, 5, 206607)),
        ),
        migrations.AlterField(
            model_name='cardverify',
            name='date_expiring',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 20, 8, 5, 207767)),
        ),
    ]
