# Generated by Django 3.2.7 on 2022-01-12 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_tokens', '0025_auto_20211214_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtoken',
            name='date_expiring',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 17, 15, 16, 57471)),
        ),
        migrations.AlterField(
            model_name='cardverify',
            name='date_expiring',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 16, 21, 16, 58209)),
        ),
    ]
