# Generated by Django 3.2.7 on 2022-01-29 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_tokens', '0029_auto_20220118_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtoken',
            name='date_expiring',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 17, 16, 29, 714445)),
        ),
        migrations.AlterField(
            model_name='cardverify',
            name='date_expiring',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 16, 22, 29, 715238)),
        ),
    ]
