# Generated by Django 3.2.7 on 2022-02-03 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp_tokens', '0031_auto_20220131_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtoken',
            name='date_expiring',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 23, 54, 41, 775801)),
        ),
        migrations.AlterField(
            model_name='cardverify',
            name='date_expiring',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 23, 0, 41, 776489)),
        ),
    ]
