# Generated by Django 3.2.7 on 2022-02-07 05:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('otp_tokens', '0034_auto_20220207_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtoken',
            name='date_expiring',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 6, 42, 52, 407838)),
        ),
        migrations.AlterField(
            model_name='cardtoken',
            name='date_issued',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 5, 36, 52, 407787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cardverify',
            name='date_expiring',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 6, 42, 52, 408638)),
        ),
    ]
