# Generated by Django 3.2.7 on 2021-10-09 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=255)),
                ('date_expiring', models.DateField()),
                ('date_issued', models.DateField()),
                ('verified', models.BooleanField()),
                ('issuing_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.issuingorginization')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_issued'],
            },
        ),
    ]
