# Generated by Django 3.2.7 on 2021-11-08 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_issuingorginizationotp'),
        ('cards', '0002_alter_cards_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11)),
                ('date_approved', models.DateField()),
                ('approved', models.BooleanField()),
                ('reason_for_visit', models.TextField()),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('issuing_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.issuingorginizationotp')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_approved'],
            },
        ),
    ]
