# Generated by Django 3.2.7 on 2021-11-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cardsotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsotp',
            name='date_approved',
            field=models.DateField(null=True),
        ),
    ]
