# Generated by Django 3.2.7 on 2021-11-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_cardsotp_date_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardsotp',
            options={'ordering': ['from_date']},
        ),
    ]
