# Generated by Django 3.2.7 on 2022-01-12 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0005_alter_cardsotp_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardsOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_download', models.DateTimeField()),
                ('created', models.BooleanField(null=True)),
                ('deleted', models.BooleanField(null=True)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.cards')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
