# Generated by Django 3.2.7 on 2022-01-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_cardsoffline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardsoffline',
            old_name='card_id',
            new_name='card',
        ),
    ]
