# Generated by Django 3.2.7 on 2022-01-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_rename_card_id_cardsoffline_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsoffline',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
